sudo: required
services:
- docker
language: bash
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
- export REPO=zepp/rpi-slackin
- docker build -t $REPO:$TAG .
after_success:
- docker login -u="$HUB_USER" -p="$HUB_PASS"
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
notifications:
  slack:
    rooms:
      secure: gt7GOLM+R27HhRNmFrWJr1GJ0SfjKF/m/1AI5U+IkYhisInA+z0eReoKmy+x3nMLjOep7qtLbwaXjTY53Ctwm1HtzJ+FR1pUGSzwb5Fp0htvaeAg5w082FoIP8pmtFmbaroyRiaYUQtaR/Ae8eeieU7jV2FsXb6/Gs2UHxokz/N6VG4TNFa9C5CqaZSveIgQ8MN0o+EF8oJu6Zojnf1j/yKysYUsNCupAE5BaV4+4Kf3IZria/YW4thysj22F9Bm+uebiEXnezEhM4MV5mQxohGqiPC/YGdV8OnLS9azLmz+Xamh94cGUICJdbAWzeEAKcAxS9rujzPDV7ITn3582uZJ9DavAS8JzYFKbIzvmaIxJMTyVH59g7SvV6h1jGkPz1bBdAGk4nht/8Rv5ehQudaw94Us1gduPi6uAOMqKwQUC6WuyOZ8UTB0+8oOFQtYZ0Am9jEXFRWx/qs61gU2HSR10YqI1j1r5FUPPfO7AXrLEnbhUiu9ml8vGizo0cKLFboatxiyCE+LwWpeEc/MNcm4dDXAapDXsbvVeQkMQM72VErPSW1X+fNpzpedulMCsJcVKnd69LblOjT2l0G06EHVTJ6dj96wrt9X83HtXK5gJfbW9EHXR6i8x1MHUeD+8d/kDe5ViTmSXPz0maFkfJ8bM5tU91T+HviD0ZH8QIU=
    template:
    - "%{repository} (%{commit}) : %{message} "
    - 'Build number: %{build_number} - Commit message: %{commit_message}'
    - 'Runtime: %{elapsed_time}'
    - 'Build details: %{build_url}'
